### ISSUE TITLE
Problems with VS 2017

### ISSUE THREAD

**Issue by jacobwvandijk** [keyboardDrummer/DebtRatchet#1]
Hi dear key board drummer

I managed to get the code compiled with VS 2017 with some small fixes. But I seem to have an issue with running the statistics provider on my solution. I do not get any output, and no exceptions are raised during a debug session. Probably I need to upgrade all nuget packages to more recent versions.
But I do not have luck with that either, I am stuck ...

Any change you can look into that?

Maybe good to mention that I target a solution that uses.Net 4.7.1.

**Comment by keyboardDrummer** [comment]
Hi there Jacob, long time no see ;)

So, you're saying that although you had this working with an older version of 2017, it broke with the newest version?

I'll have a look, but it'll be tomorrow evening.

**Comment by jacobwvandijk** [comment]
Hi Remy, indeed. We are still fan of this project (o;

You are correct. We did upgrade to 4.7.1 recently  and it seems to have broken down. We were using the old 'DebtAnalyzer', so I updated to DebtRatchet and fetched the code in an attempt to fix it myself.

The analyzer works OK in VS itself. I get the red lines perfectly. No worries there.
The attrribute updater and the statistics provider do not seem to work,. They just end quietly with no effect (and no exceptions ....). We are using the new language features so I guess our project cannot be read properly anymore

The error I get when I try to upgrade all packages is the following:

_Could not install package 'Microsoft.CodeAnalysis.Common 2.6.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile7', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author._

Not sure if this is the way to go any way.

Many thanks for having a look.

**Comment by jacobwvandijk** [comment]
Maybe a small addendum, where the problem started was that the current attribute updater and statistics provider are using somehow VS 2015. I have a new laptop and do not have VS 2015 anymore, only VS 2017. That is probably the reason it went undetected.

**Comment by keyboardDrummer** [comment]
I've made some updates that I hope will resolve your issue:
- Updated all NuGet packages to the latest version
- Updated the projects to the new .csproj format
- Updated the project target frameworks to 4.7.1
- Made fixes to AttributeUpdater and StatisticsProvider

These changes make the analyser, AttributeUpdater and StatisticsProvider work well on a fresh 2017 solution. I'm guessing the analyzer won't work on VS 2015 any more.

**Comment by jacobwvandijk** [comment]
Thx. I have no longer issues with something requiring VS 2017. I have an issue however with the attribute updater; getting an argument exception during the iteration over de VS projects of our solution. Somewhere halfway the exception is raised because a duplicate key already has been added. I have to see if there is something wrong with are code (probably (o; )

It's thrown somewhere during ' await project.GetCompilationAsync();' 

in a class 

 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.SolutionState.CompilationTracker

and is some sort of dictionary

 	mscorlib.dll!System.Collections.Generic.Dictionary<Microsoft.CodeAnalysis.MetadataReference, Microsoft.CodeAnalysis.ProjectId>.Insert(Microsoft.CodeAnalysis.MetadataReference key, Microsoft.CodeAnalysis.ProjectId value, bool add)	

Does it ring any bell's?

**Comment by keyboardDrummer** [comment]
O that's curious. What's the exact exception you get? 

It sounds like [this bug](https://github.com/dotnet/roslyn/issues/16010) is troubling you. Can you see which project it's failing at, or does .NET still not tell you which key is giving the ArgumentException? ^^

You could try attaching a debugger to visual studio and have it break on the ArgumentException. Or you could run the AttributeUpdater from source with a debugger attached.

**Comment by jacobwvandijk** [comment]
Hi Remy, that is exactly what is troubling me. Thanks for pointing to this direction. I have removed al references in the project that was causing problems and re-added the references one by one. I ended up with a lot less references any way. It is working now. Thanks a lot.

**Comment by keyboardDrummer** [comment]
Awesome :)
